### ISSUE TITLE
Customer section bug fixes

### ISSUE THREAD

**Issue by gudzsv** [gudzsv/food-sta-vite-team#8]
## Знайшов декілька деталей по секції які слід підправити макет [Figma(тут)](https://www.figma.com/file/utiHvBtEHmD5ztYeL5V95X/food-delivery-service-(GoIT)-(Copy)?node-id=480%3A6477&mode=dev)

_1) В `HTML `необхідно виправити шлях до картинок замість двох крапок `src="../img/customers/Divider.svg" ` залишити одну крапку та слеш `src="./img/customers/Divider.svg"` тому що на разі картинка не відображається_

![image](https://github.com/gudzsv/food-sta-vite-team/assets/49489543/e4115209-15f6-4705-ba12-536afda4e35c)
![image](https://github.com/gudzsv/food-sta-vite-team/assets/49489543/7bc42aef-e30b-4117-bf06-bd7c2b7298bf)

_2) Також в тебе в `HTML `потрібно перейменувати клас  `conteiner `на `container` (стилі саме на цей налаштовані)_

![image](https://github.com/gudzsv/food-sta-vite-team/assets/49489543/bf980977-6edb-47e4-a366-12f659960bfc)

_3) А щоб контейнер став по центру то потрібно з класу ` .customers-container`  видалити `margin-left` який перебиває властивість основного контейнера що позиціонує блок по центру_

```css
.customers-container {
     margin-left: 32px;   /* прибрати цю властивість так як вона перебиває властивість margin з класу container */
}
``` 
_4) Ще можна з класу `.customers-card` прибрати висоту щоб він тягнувся в залежності від контенту і тоді падінг з класу `.customers-say`  буде не буде притискати_ 

```css
.customers-card {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 501px;
    height: 232px;   /* ось це прибрати*/
    border-radius: 0 30px 30px;
    background-color: #fefefe;
}
``` 
5) Також в класі `.avatar-content` потрібно вирівняти контент згідно макету 

```css
.avatar-content {
    display: block;
    margin: auto 0; /*додати властивість щоб вирівняти по вертикалі в центрі*/
    padding-left: 16px;
    padding-right: 14px;
}
``` 

_Зараз контетн вгорі_ 

![image](https://github.com/gudzsv/food-sta-vite-team/assets/49489543/53a22439-a9fd-40a7-bbab-8a433d7e15ee)

_по макету має бути по центрі блоку як тут_ 

![image](https://github.com/gudzsv/food-sta-vite-team/assets/49489543/e1d7b120-3a40-45eb-a974-f1900f2648d8)
